name: Bible Beasts Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application
        uses: actions/checkout@v4

      - name: Build Bible Beasts and Publish Image
        run: |
          docker login --username norlinga --password ${{ secrets.GHCR_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/norlinga/bible-beasts:latest
          docker push ghcr.io/norlinga/bible-beasts:latest
